# Generated by Django 4.2.25 on 2025-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_channels',
            field=models.JSONField(blank=True, default=list, help_text="Lista de canales seleccionados, ej: ['email', 'whatsapp']"),
        ),
    ]
