# Generated by Django 4.2.25 on 2025-11-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready to ship', 'Ready to ship'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
