# Generated by Django 4.2.25 on 2025-11-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
