# Generated by Django 4.2.25 on 2025-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_shipping_address_orders_shipping_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='notification_channels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
